// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gsProbs
Rcpp::NumericVector gsProbs(const double p, const Rcpp::IntegerVector& sizes, const Rcpp::IntegerVector& crits);
RcppExport SEXP dbSamplr_gsProbs(SEXP pSEXP, SEXP sizesSEXP, SEXP critsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type sizes(sizesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type crits(critsSEXP);
    __result = Rcpp::wrap(gsProbs(p, sizes, crits));
    return __result;
END_RCPP
}
