# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate simple multiple testing strategy for single binomial event
#'
#' @param p event probability
#' @param sizes monotonically increasing vector of sample sizes
#' @param crits vector below which sampling stops
#' @return a vector giving probability of stopping at each sample
#' @export
gsProbs <- function(p, sizes, crits) {
    .Call('dbSamplr_gsProbs', PACKAGE = 'dbSamplr', p, sizes, crits)
}

